// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SLSKDONET.Data;

#nullable disable

namespace SLSKDONET.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251225220040_AddQueuePersistence")]
    partial class AddQueuePersistence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("SLSKDONET.Data.Entities.SpotifyMetadataCacheEntity", b =>
                {
                    b.Property<string>("SpotifyId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CachedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.HasKey("SpotifyId");

                    b.ToTable("SpotifyMetadataCache");
                });

            modelBuilder.Entity("SLSKDONET.Data.LibraryEntryEntity", b =>
                {
                    b.Property<string>("UniqueHash")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Album")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AlbumArtUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ArtistImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("AudioFingerprint")
                        .HasColumnType("TEXT");

                    b.Property<double?>("BPM")
                        .HasColumnType("REAL");

                    b.Property<int>("Bitrate")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CanonicalDuration")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Danceability")
                        .HasColumnType("REAL");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Energy")
                        .HasColumnType("REAL");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FilePathUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Genres")
                        .HasColumnType("TEXT");

                    b.Property<string>("ISRC")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Integrity")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnriched")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUsedAt")
                        .HasColumnType("TEXT");

                    b.Property<double?>("ManualBPM")
                        .HasColumnType("REAL");

                    b.Property<string>("ManualKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("MusicalKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFilePath")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Popularity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpotifyAlbumId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpotifyArtistId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("SpotifyBPM")
                        .HasColumnType("REAL");

                    b.Property<string>("SpotifyKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpotifyTrackId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("Valence")
                        .HasColumnType("REAL");

                    b.HasKey("UniqueHash");

                    b.ToTable("LibraryEntries");
                });

            modelBuilder.Entity("SLSKDONET.Data.LibraryHealthEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BronzeCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FreeStorageBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoldCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HqTracks")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastScanDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PendingUpdates")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SilverCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TopGenresJson")
                        .HasColumnType("TEXT");

                    b.Property<long>("TotalStorageBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalTracks")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UpgradableCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("LibraryHealth");
                });

            modelBuilder.Entity("SLSKDONET.Data.PlaylistActivityLogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlaylistId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlaylistId");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("SLSKDONET.Data.PlaylistJobEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AlbumArtUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateStarted")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinationFolder")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsUserPaused")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MissingCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("SuccessfulCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalTracks")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_PlaylistJob_CreatedAt");

                    b.ToTable("PlaylistJobs");
                });

            modelBuilder.Entity("SLSKDONET.Data.PlaylistTrackEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Album")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AlbumArtUrl")
                        .HasColumnType("TEXT");

                    b.Property<double?>("AnalysisOffset")
                        .HasColumnType("REAL");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ArtistImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("AudioFingerprint")
                        .HasColumnType("TEXT");

                    b.Property<double?>("BPM")
                        .HasColumnType("REAL");

                    b.Property<int>("Bitrate")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BitrateScore")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CanonicalDuration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CuePointsJson")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Danceability")
                        .HasColumnType("REAL");

                    b.Property<double?>("Energy")
                        .HasColumnType("REAL");

                    b.Property<string>("Format")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FrequencyCutoff")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Genres")
                        .HasColumnType("TEXT");

                    b.Property<string>("ISRC")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnriched")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLiked")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsTrustworthy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastPlayedAt")
                        .HasColumnType("TEXT");

                    b.Property<double?>("ManualBPM")
                        .HasColumnType("REAL");

                    b.Property<string>("ManualKey")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MinBitrateOverride")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MusicalKey")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PlaylistId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Popularity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PreferredFormats")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("QualityConfidence")
                        .HasColumnType("REAL");

                    b.Property<string>("QualityDetails")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolvedFilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("SourcePlaylistId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourcePlaylistName")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpectralHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpotifyAlbumId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpotifyArtistId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("SpotifyBPM")
                        .HasColumnType("REAL");

                    b.Property<string>("SpotifyKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpotifyTrackId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TrackNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TrackUniqueHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("Valence")
                        .HasColumnType("REAL");

                    b.Property<byte[]>("WaveformData")
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("PlaylistId")
                        .HasDatabaseName("IX_PlaylistTrack_PlaylistId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_PlaylistTrack_Status");

                    b.HasIndex("TrackUniqueHash");

                    b.ToTable("PlaylistTracks");
                });

            modelBuilder.Entity("SLSKDONET.Data.QueueItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCurrentTrack")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PlaylistTrackId")
                        .HasColumnType("TEXT");

                    b.Property<int>("QueuePosition")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("QueueItems");
                });

            modelBuilder.Entity("SLSKDONET.Data.TrackEntity", b =>
                {
                    b.Property<string>("GlobalId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("AlbumArtUrl")
                        .HasColumnType("TEXT");

                    b.Property<double?>("AnalysisOffset")
                        .HasColumnType("REAL");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ArtistImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("AudioFingerprint")
                        .HasColumnType("TEXT");

                    b.Property<double?>("BPM")
                        .HasColumnType("REAL");

                    b.Property<int>("Bitrate")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BitrateScore")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CanonicalDuration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoverArtUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("CuePointsJson")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Danceability")
                        .HasColumnType("REAL");

                    b.Property<double?>("Energy")
                        .HasColumnType("REAL");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("FrequencyCutoff")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Genres")
                        .HasColumnType("TEXT");

                    b.Property<string>("ISRC")
                        .HasColumnType("TEXT");

                    b.Property<int>("Integrity")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnriched")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsTrustworthy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastUpgradeAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUpgradeScanAt")
                        .HasColumnType("TEXT");

                    b.Property<double?>("ManualBPM")
                        .HasColumnType("REAL");

                    b.Property<string>("ManualKey")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MinBitrateOverride")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MusicalKey")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextRetryTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Popularity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PreferredFormats")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousBitrate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("QualityConfidence")
                        .HasColumnType("REAL");

                    b.Property<string>("QualityDetails")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SoulseekUsername")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SourcePlaylistId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourcePlaylistName")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpectralHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpotifyAlbumId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpotifyArtistId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("SpotifyBPM")
                        .HasColumnType("REAL");

                    b.Property<string>("SpotifyKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpotifyTrackId")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpgradeSource")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Valence")
                        .HasColumnType("REAL");

                    b.HasKey("GlobalId");

                    b.ToTable("Tracks");
                });

            modelBuilder.Entity("SLSKDONET.Data.PlaylistActivityLogEntity", b =>
                {
                    b.HasOne("SLSKDONET.Data.PlaylistJobEntity", "Job")
                        .WithMany()
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("SLSKDONET.Data.PlaylistTrackEntity", b =>
                {
                    b.HasOne("SLSKDONET.Data.PlaylistJobEntity", "Job")
                        .WithMany("Tracks")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("SLSKDONET.Data.PlaylistJobEntity", b =>
                {
                    b.Navigation("Tracks");
                });
#pragma warning restore 612, 618
        }
    }
}
